"""Offline licence keys for the desktop edition.

A key is derived from the buyer's e-mail with an HMAC secret that only the seller has (secrets.json
"license_secret"; build_app.bat bakes a copy into the .exe as app/_secret.py, which is git-ignored).
This keeps honest people honest; it is not DRM. Without a key the app runs as a 14-day trial."""
from __future__ import annotations

import base64
import datetime as dt
import hashlib
import hmac

try:
    from _secret import LICENSE_SECRET  # generated by build_app.bat, never committed
except Exception:  # noqa: BLE001
    LICENSE_SECRET = "dev-secret-not-for-sale"

TRIAL_DAYS = 14


def normalize_email(email: str) -> str:
    return (email or "").strip().lower()


def make_key(email: str, secret: str = LICENSE_SECRET) -> str:
    """BDF-XXXXX-XXXXX-XXXXX, derived from the e-mail."""
    digest = hmac.new(secret.encode("utf-8"), normalize_email(email).encode("utf-8"), hashlib.sha256).digest()
    raw = base64.b32encode(digest).decode("ascii").rstrip("=")[:15]
    return "BDF-" + "-".join(raw[i:i + 5] for i in range(0, 15, 5))


def valid(email: str, key: str, secret: str = LICENSE_SECRET) -> bool:
    if not email or not key:
        return False
    want = make_key(email, secret)
    got = (key or "").strip().upper().replace(" ", "")
    return hmac.compare_digest(want, got)


def trial_days_left(trial_started: str) -> int:
    """Days of trial left given the ISO date the trial started (stored in the app config)."""
    try:
        start = dt.date.fromisoformat(trial_started)
    except (TypeError, ValueError):
        return TRIAL_DAYS
    return max(0, TRIAL_DAYS - (dt.date.today() - start).days)
